# Generated by Django 6.1 on 2026-08-18 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('provider_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_url', models.URLField(blank=True, default='', max_length=255)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('rate_limit_rpm', models.PositiveIntegerField(default=60)),
                ('rate_limit_daily', models.PositiveIntegerField(default=1000)),
                ('current_daily_uses', models.PositiveIntegerField(default=0)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited')], default='healthy', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrichmentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial Failure'), ('failed', 'Failed')], default='running', max_length=20)),
                ('providers_used', models.JSONField(blank=True, default=list)),
                ('contacts_found', models.PositiveIntegerField(default=0)),
                ('stored_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_logs', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_runs', to='enrichment.company')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('provider_source', models.CharField(help_text='Source provider (pdl, contactout, apollo)', max_length=50)),
                ('verification_state', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('failed', 'Verification Failed')], default='unverified', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='enrichment.company')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'email'], name='contacts_company_b3cd1e_idx'), models.Index(fields=['provider_source'], name='contacts_provide_6f4603_idx'), models.Index(fields=['verification_state'], name='contacts_verific_81dbca_idx')],
            },
        ),
    ]
