# Generated by Django 6.1 on 2026-08-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0002_seed_enrichment_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentrun',
            name='call_logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
