# Generated by Django 6.1 on 2026-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0004_seed_lusha_enrichment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='provider_source',
            field=models.CharField(help_text='Source provider (pdl, contactout, apollo, lusha)', max_length=50),
        ),
    ]
