# Generated by Django 6.1 on 2026-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0005_alter_contact_provider_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentrun',
            name='pending_phone_requests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
