# Generated by Django 6.1 on 2026-08-17 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('provider_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_url', models.URLField(blank=True, default='', max_length=255)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('rate_limit_rpm', models.PositiveIntegerField(default=60)),
                ('rate_limit_daily', models.PositiveIntegerField(default=1000)),
                ('current_daily_uses', models.PositiveIntegerField(default=0)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited')], default='healthy', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
