# Generated by Django 6.1 on 2026-08-25 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingestionrun_rawjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(blank=True, default='', max_length=500)),
                ('company_name_raw', models.CharField(blank=True, default='', max_length=255)),
                ('location_raw', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('seniority', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('experience_text', models.CharField(blank=True, default='', max_length=255)),
                ('salary_text', models.CharField(blank=True, default='', max_length=255)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=20)),
                ('classification_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='MasterCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='MasterJobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.CharField(max_length=500, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('normalized', models.CharField(db_index=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['normalized'],
            },
        ),
        migrations.CreateModel(
            name='MasterTechnology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_category', models.CharField(blank=True, default='', max_length=255)),
                ('primary_technologies', models.JSONField(blank=True, default=list)),
                ('secondary_technologies', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('classification_method', models.CharField(choices=[('rules', 'Deterministic Rules'), ('llm', 'LLM Classification'), ('hybrid', 'Hybrid')], default='rules', max_length=20)),
                ('raw_llm_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='core.canonicaljob')),
            ],
        ),
        migrations.CreateModel(
            name='JobDemandMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_category', models.CharField(db_index=True, max_length=255)),
                ('period_days', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('active_jobs_start', models.PositiveIntegerField(default=0)),
                ('active_jobs_end', models.PositiveIntegerField(default=0)),
                ('new_postings', models.PositiveIntegerField(default=0)),
                ('expired_postings', models.PositiveIntegerField(default=0)),
                ('net_change', models.IntegerField(default=0)),
                ('change_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('role_category', 'period_days', 'period_start')},
            },
        ),
        migrations.AddField(
            model_name='canonicaljob',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_jobs', to='core.mastercompany'),
        ),
        migrations.AddField(
            model_name='canonicaljob',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_jobs', to='core.masterlocation'),
        ),
        migrations.CreateModel(
            name='MasterSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='core.mastertechnology')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.canonicaljob')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot_date'], name='core_jobsna_snapsho_4ec6d4_idx')],
                'unique_together': {('canonical_job', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='JobSourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_code', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, default='')),
                ('dedup_match_type', models.CharField(choices=[('url_exact', 'URL Exact'), ('strong_signal', 'Company+Title+Location+Date'), ('description_sim', 'Description Similarity'), ('none', 'No Match (New)')], default='none', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='core.canonicaljob')),
                ('raw_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_record', to='core.rawjob')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_code', 'external_id'], name='core_jobsou_provide_08eeb7_idx'), models.Index(fields=['canonical_job'], name='core_jobsou_canonic_e5bab1_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployerHiringScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_postings', models.PositiveIntegerField(default=0)),
                ('active_postings', models.PositiveIntegerField(default=0)),
                ('unique_roles', models.PositiveIntegerField(default=0)),
                ('hiring_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_scores', to='core.mastercompany')),
            ],
            options={
                'ordering': ['-hiring_score'],
                'unique_together': {('company', 'period_start', 'period_end')},
            },
        ),
        migrations.AddIndex(
            model_name='canonicaljob',
            index=models.Index(fields=['status'], name='core_canoni_status_4a2b38_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaljob',
            index=models.Index(fields=['normalized_title'], name='core_canoni_normali_928837_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaljob',
            index=models.Index(fields=['company'], name='core_canoni_company_5057cd_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaljob',
            index=models.Index(fields=['location'], name='core_canoni_locatio_262075_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaljob',
            index=models.Index(fields=['-last_seen'], name='core_canoni_last_se_c699c4_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaljob',
            index=models.Index(fields=['work_mode'], name='core_canoni_work_mo_9f1ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicaljob',
            index=models.Index(fields=['seniority'], name='core_canoni_seniori_4d89e6_idx'),
        ),
    ]
